from paraview.simple import *
paraview.simple._DisableFirstRenderCameraReset()
renderView1 = GetActiveViewOrCreate('RenderView')
animationScene1 = GetAnimationScene()
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/77.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/78.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/79.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/80.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/81.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/82.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/83.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/84.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/85.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/86.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/87.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/88.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/89.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/90.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/91.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/92.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/93.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/94.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/95.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/96.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/97.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/98.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/99.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/100.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/101.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/102.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/103.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/104.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/105.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/106.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/107.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/108.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/109.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/110.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/111.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/112.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/113.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/114.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/115.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/116.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/117.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/118.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/119.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/120.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/121.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/122.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/123.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/124.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/125.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/126.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/127.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/128.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/129.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/130.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/131.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/132.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/133.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/134.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/135.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/136.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/137.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/138.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/139.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/140.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/141.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/142.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/143.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/144.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/145.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/146.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/147.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/148.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/149.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/150.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/151.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/152.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/153.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/154.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/155.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/156.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/157.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/158.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/159.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/160.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/161.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/162.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/163.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/164.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/165.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/166.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/167.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/168.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/169.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/170.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/171.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/172.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/173.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/174.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/175.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/176.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/177.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/178.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/179.png', renderView1, ImageResolution=[1563, 576])
animationScene1.GoToNext()
SaveScreenshot('C:/Users/Zhizhong.Ding/Desktop/figures/180.png', renderView1, ImageResolution=[1563, 576])
